/********************************************************************
*       Filename: ClientGui.java                                    *
*       Author: Tejas Dwarkaram                                     *
*       Date: 20 July 2012, 09:10                                   *
*       Operating System: Windows XP Professional                   *
*       Java Version: JDK 1.5 Update 9                              *
*       Description: Creating the Gui for the client application    *
********************************************************************/

import java.io.IOException;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//importing the required packages

/**
 * Holds the constructors and methods required to create the Graphical User Interface for the client side application
 * @author Tejas
 * @version 0.1 07/08/2012
 * @since JDK 1.5
 */
public class ClientGui extends javax.swing.JFrame 
{
    /**
     * Creates new form ClientGui
     */
    public ClientGui() 
    {
        //initializing the components
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        headingLbl = new javax.swing.JLabel();
        allComponentPnl = new javax.swing.JPanel();
        allTbPne = new javax.swing.JTabbedPane();
        loginPnl = new javax.swing.JPanel();
        usernameFld = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        infoLbl = new javax.swing.JLabel();
        passwordFld = new javax.swing.JPasswordField();
        addPnl = new javax.swing.JPanel();
        tabAdd = new javax.swing.JTabbedPane();
        addRecordPnl = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        movieidFld = new javax.swing.JTextField();
        movienameFld = new javax.swing.JTextField();
        genreidFld = new javax.swing.JTextField();
        movieDescripScrlPne = new javax.swing.JScrollPane();
        moviedescripTxtArea = new javax.swing.JTextArea();
        logoutBtn = new javax.swing.JButton();
        deleteRecordPnl = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        deleteMovieNameTxtFld = new javax.swing.JTextField();
        searchPnl = new javax.swing.JPanel();
        searchFld = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clientMnuBar = new javax.swing.JMenuBar();
        mainMnuItm = new javax.swing.JMenu();
        closeMnuItm = new javax.swing.JMenuItem();
        helpMnu = new javax.swing.JMenu();
        aboutMnuItm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Client Application");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("clientFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        headingLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        headingLbl.setForeground(new java.awt.Color(255, 0, 0));
        headingLbl.setText("Ins-Pirate-D Video Store");

        allComponentPnl.setBackground(new java.awt.Color(0, 0, 0));
        loginPnl.setBackground(new java.awt.Color(197, 198, 197));
        loginPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        usernameFld.setText("Username");
        usernameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameFldMouseExited(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        infoLbl.setFont(new java.awt.Font("Tahoma", 1, 12));
        infoLbl.setText("Login as Administrator here");

        org.jdesktop.layout.GroupLayout loginPnlLayout = new org.jdesktop.layout.GroupLayout(loginPnl);
        loginPnl.setLayout(loginPnlLayout);
        loginPnlLayout.setHorizontalGroup(
            loginPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, loginPnlLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .add(infoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(165, 165, 165))
            .add(loginPnlLayout.createSequentialGroup()
                .add(157, 157, 157)
                .add(loginPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(passwordFld)
                    .add(usernameFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
            .add(loginPnlLayout.createSequentialGroup()
                .add(182, 182, 182)
                .add(loginBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        loginPnlLayout.setVerticalGroup(
            loginPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginPnlLayout.createSequentialGroup()
                .add(39, 39, 39)
                .add(infoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(usernameFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(passwordFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        allTbPne.addTab("Login", loginPnl);

        addPnl.setBackground(new java.awt.Color(197, 198, 197));
        addPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        addPnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addPnlComponentShown(evt);
            }
        });

        tabAdd.setName("adminTab");
        addRecordPnl.setName("addTab");
        addRecordPnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addRecordPnlComponentShown(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        movieidFld.setText("Movie ID");
        movieidFld.setEnabled(false);
        movieidFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieidFldMouseClicked(evt);
            }
        });

        movienameFld.setText("Movie Name");
        movienameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movienameFldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                movienameFldMouseExited(evt);
            }
        });

        genreidFld.setText("Genre ID");
        genreidFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genreidFldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genreidFldMouseExited(evt);
            }
        });

        moviedescripTxtArea.setColumns(20);
        moviedescripTxtArea.setRows(5);
        moviedescripTxtArea.setText("Movie Description\n");
        moviedescripTxtArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviedescripTxtAreaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moviedescripTxtAreaMouseExited(evt);
            }
        });

        movieDescripScrlPne.setViewportView(moviedescripTxtArea);

        logoutBtn.setText("Logout");

        org.jdesktop.layout.GroupLayout addRecordPnlLayout = new org.jdesktop.layout.GroupLayout(addRecordPnl);
        addRecordPnl.setLayout(addRecordPnlLayout);
        addRecordPnlLayout.setHorizontalGroup(
            addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addRecordPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(addRecordPnlLayout.createSequentialGroup()
                        .add(movieDescripScrlPne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(addBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(logoutBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .add(addRecordPnlLayout.createSequentialGroup()
                        .add(addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, genreidFld)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, movienameFld)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, movieidFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .add(180, 180, 180)))
                .addContainerGap())
        );
        addRecordPnlLayout.setVerticalGroup(
            addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, addRecordPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(movieidFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movienameFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(genreidFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                .add(addRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(addRecordPnlLayout.createSequentialGroup()
                        .add(addBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(logoutBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(movieDescripScrlPne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tabAdd.addTab("Add Record", null, addRecordPnl, "Add a record");

        deleteBtn.setText("Delete");
        deleteBtn.setMaximumSize(new java.awt.Dimension(51, 23));
        deleteBtn.setMinimumSize(new java.awt.Dimension(51, 23));
        deleteBtn.setPreferredSize(new java.awt.Dimension(51, 23));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        deleteMovieNameTxtFld.setText("Enter the name of the movie you wish to delete");

        org.jdesktop.layout.GroupLayout deleteRecordPnlLayout = new org.jdesktop.layout.GroupLayout(deleteRecordPnl);
        deleteRecordPnl.setLayout(deleteRecordPnlLayout);
        deleteRecordPnlLayout.setHorizontalGroup(
            deleteRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deleteRecordPnlLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .add(deleteMovieNameTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(89, 89, 89))
            .add(deleteRecordPnlLayout.createSequentialGroup()
                .add(185, 185, 185)
                .add(deleteBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        deleteRecordPnlLayout.setVerticalGroup(
            deleteRecordPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deleteRecordPnlLayout.createSequentialGroup()
                .add(89, 89, 89)
                .add(deleteMovieNameTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(deleteBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        tabAdd.addTab("Delete Record", null, deleteRecordPnl, "Delete a record");

        org.jdesktop.layout.GroupLayout addPnlLayout = new org.jdesktop.layout.GroupLayout(addPnl);
        addPnl.setLayout(addPnlLayout);
        addPnlLayout.setHorizontalGroup(
            addPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabAdd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        addPnlLayout.setVerticalGroup(
            addPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabAdd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        allTbPne.addTab("Admin", addPnl);

        searchPnl.setBackground(new java.awt.Color(197, 198, 197));
        searchFld.setFont(new java.awt.Font("Tahoma", 0, 12));
        searchFld.setText("Enter your search word here");
        searchFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchFldMouseExited(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout searchPnlLayout = new org.jdesktop.layout.GroupLayout(searchPnl);
        searchPnl.setLayout(searchPnlLayout);
        searchPnlLayout.setHorizontalGroup(
            searchPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPnlLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .add(searchFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(150, 150, 150))
            .add(searchPnlLayout.createSequentialGroup()
                .add(210, 210, 210)
                .add(searchBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        searchPnlLayout.setVerticalGroup(
            searchPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPnlLayout.createSequentialGroup()
                .add(119, 119, 119)
                .add(searchFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(searchBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        allTbPne.addTab("Search", searchPnl);

        org.jdesktop.layout.GroupLayout allComponentPnlLayout = new org.jdesktop.layout.GroupLayout(allComponentPnl);
        allComponentPnl.setLayout(allComponentPnlLayout);
        allComponentPnlLayout.setHorizontalGroup(
            allComponentPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(allComponentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(allTbPne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        allComponentPnlLayout.setVerticalGroup(
            allComponentPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(allComponentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(allTbPne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 349, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMnuItm.setText("Menu");
        closeMnuItm.setText("Close");
        closeMnuItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMnuItmActionPerformed(evt);
            }
        });

        mainMnuItm.add(closeMnuItm);

        clientMnuBar.add(mainMnuItm);

        helpMnu.setText("Help");
        aboutMnuItm.setText("About");
        aboutMnuItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMnuItmActionPerformed(evt);
            }
        });

        helpMnu.add(aboutMnuItm);

        clientMnuBar.add(helpMnu);

        setJMenuBar(clientMnuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, allComponentPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, headingLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(headingLbl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(allComponentPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        protocolSend(3);
    }//GEN-LAST:event_deleteBtnActionPerformed

    //method called when the Add button is clicked
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(Pattern.matches("[A-Z]{1}", movienameFld.getText()) & Pattern.matches("\\d", genreidFld.getText())) 
        {
            protocolSend(2);
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Movie name should start with a capital letter", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    //method called if the mouse is clicked on this Text Field
    private void movieidFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieidFldMouseClicked
        if((movieidFld.getText()).equals("Movie ID")) 
        {
            movieidFld.setText("");
        }
    }//GEN-LAST:event_movieidFldMouseClicked

    //method called if 
    private void movienameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movienameFldMouseClicked
        if((movienameFld.getText()).equals("Movie Name")) 
        {
            movienameFld.setText("");
        }
    }//GEN-LAST:event_movienameFldMouseClicked

    private void movienameFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movienameFldMouseExited
        if((movienameFld.getText()).equals("")) 
        {
            movienameFld.setText("Movie Name");
        }
    }//GEN-LAST:event_movienameFldMouseExited

    private void genreidFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreidFldMouseClicked
        if((genreidFld.getText()).equals("Genre ID")) 
        {
            genreidFld.setText("");
        }
    }//GEN-LAST:event_genreidFldMouseClicked

    private void genreidFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreidFldMouseExited
        if(((genreidFld.getText()).equals("")) || ((genreidFld.getText()).equals(" "))) 
        {
            genreidFld.setText("Genre ID");
        }
    }//GEN-LAST:event_genreidFldMouseExited

    private void moviedescripTxtAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviedescripTxtAreaMouseClicked
        if((moviedescripTxtArea.getText()).equals("Movie Description")) 
        {
            moviedescripTxtArea.setText("");
        }
    }//GEN-LAST:event_moviedescripTxtAreaMouseClicked

    private void moviedescripTxtAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviedescripTxtAreaMouseExited
        if((moviedescripTxtArea.getText()).equals(" ")) 
        {
            moviedescripTxtArea.setText("Movie Description");
        }
    }//GEN-LAST:event_moviedescripTxtAreaMouseExited

    private void addRecordPnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addRecordPnlComponentShown
        protocolSend(4);
    }//GEN-LAST:event_addRecordPnlComponentShown

    private void addPnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addPnlComponentShown
        protocolSend(4);
    }//GEN-LAST:event_addPnlComponentShown

    //method to execute when mouse exits the search text field
    private void searchFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFldMouseExited
        if((searchFld.getText()).equals("")) 
        {
            searchFld.setText("Enter your search word here");
        }
    }//GEN-LAST:event_searchFldMouseExited

    //method to execute when the user clicks on the search text field
    private void searchFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFldMouseClicked
        if((searchFld.getText()).equals("Enter your search word here")) 
        {
            searchFld.setText("");
        }
    }//GEN-LAST:event_searchFldMouseClicked

    //method to execute if the mouse is exited from the movie name 
    //method to execute when the login button is pressed
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        protocolSend(5);
    }//GEN-LAST:event_loginBtnActionPerformed

    //method to execute if the menu item '1' is clicked
    private void aboutMnuItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMnuItmActionPerformed
        new HelpFrame().setVisible(true);
    }//GEN-LAST:event_aboutMnuItmActionPerformed

    //creating a new object array to store the 'close' options
    Object[] options = {"Minimize", "Exit", "Cancel"};
    
    //method to execute when the frame is closing 
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        windowCheck();
    }//GEN-LAST:event_formWindowClosing

    //method to exeucte when the menu item 3 is clicked
    private void closeMnuItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMnuItmActionPerformed
        windowCheck();
    }//GEN-LAST:event_closeMnuItmActionPerformed

    //creating the method to run when the exit command is called
    public void windowCheck()
    {
        int opt = JOptionPane.showOptionDialog(null, "What would you like to do ?", "You sure you want to leave ?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
        if(opt==1)
        {
            dispose();
        }
        else if(opt==0)
        {
          this.setState(JFrame.ICONIFIED);
        }
    }

    //method to execute if the mouse is exited from the username field 
    private void usernameFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFldMouseExited
        if((usernameFld.getText()).equals(""))
        {
            usernameFld.setText("Username");
        }
    }//GEN-LAST:event_usernameFldMouseExited
    
    //method to execute id the username text field is clicked
    private void usernameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFldMouseClicked
        if(((usernameFld.getText()).equals("Username"))||((usernameFld.getText()).equals("")))
        {
            usernameFld.setText("");
        }
    }//GEN-LAST:event_usernameFldMouseClicked
       
    //method to execute if the search button is clicked
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        protocolSend(1);
    }//GEN-LAST:event_searchBtnActionPerformed
    
    /**
     * Creates a new instance of the constructor
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        
        java.awt.EventQueue.invokeLater
        (
            new Runnable() 
            {
                public void run()
                {
                    new ClientConnect();
                    new ClientGui().setVisible(true);
                }
            }   
        );

    }
    
    /**
     * Method to convert the characters retrieved from the JPasswordField into readable String characters
     * @param pass Character Array
     * @return String variable
     */
    public String convertPassword(char[] pass)
    {
        String password ="";
        for(int x=0;x<pass.length;x++)
        {
            password = password + Character.toString(pass[x]);
        }
        return password;
    }
    
    /**
     * Method used to send the required
     * @param function int
     */
    public void protocolSend(int function) 
    {
            
        String fromServer;
        String fromUser;
        try 
        {
            if((fromServer = ClientConnect.in.readLine()) != null) 
            {
                fromUser = "0";
                if(function == 1) 
                {
                    fromUser = "1" + searchFld.getText();
                } 
                else if(function == 2) 
                {
                    fromUser = 6 + genreidFld.getText();
                    if(fromServer.equalsIgnoreCase("yes"))
                    {
                        fromUser = "2" + "'" + movienameFld.getText() + "',"  + "'" +  moviedescripTxtArea.getText() + "'," + "'" + genreidFld.getText() + "'" ;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Genre ID does not exist!");
                    }
                }
                else if(function == 4)
                {
                    fromUser = "4";
                    movieidFld.setText(fromServer);
                }
                else if(function == 5)
                {
                    fromUser = "5" + usernameFld.getText() + "+" + convertPassword(passwordFld.getPassword());
                }
                else if(function == 3)
                {
                    fromUser = "3" + deleteMovieNameTxtFld.getText();
                }
                
                System.out.println(fromServer);
                
                if(function == 2 && fromServer.equals("yes"))
                {
                    JOptionPane.showMessageDialog(null,"Record added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(function == 1)
                {
                    if(!fromServer.equals("Welcome"))
                    {   
                        if(!fromServer.equalsIgnoreCase("No"))
                        {
                            String search[] = fromServer.split("[+]");

                            Object[][] data = new Object[search.length][4];
                            String new_row[];

                            for(int _row = 0; _row != search.length; _row++)
                            {
                                    if(!search[_row].equals(null))
                                    {
                                            new_row = search[_row].split("[,]");
                                            
                                            for(int _cell = 0; _cell != new_row.length; _cell++)
                                            {
                                                data[_row][_cell] = new_row[_cell];
                                            }
                                    }
                            }
                            SearchFrame results = new SearchFrame();
                            results.setVisible(true);
                            results.showResults(data);
                        }
                        else 
                        {
                            JOptionPane.showMessageDialog(null,"No Results found for that search ! Please try again", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
		}
                else if(function==5)
                {
                    if(fromServer.equalsIgnoreCase("success"))
                    {                    
                        JOptionPane.showMessageDialog(null, "Welcome " + usernameFld.getText());
                        usernameFld.setEnabled(false);
                        passwordFld.setEnabled(false);
                        loginBtn.setVisible(false);
                        logoutBtn.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error in log in ! try again !", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                  
                if(fromServer.equals("Bye")) 
                {
                    System.exit(1);
                }
                if(fromUser != null) 
                {
                    System.out.println("\nClient: " + fromUser);               
                    ClientConnect.out.println(fromUser);
                }
            }
        }
        catch(IOException ioe){}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMnuItm;
    static javax.swing.JButton addBtn;
    public static javax.swing.JPanel addPnl;
    private javax.swing.JPanel addRecordPnl;
    private javax.swing.JPanel allComponentPnl;
    public static javax.swing.JTabbedPane allTbPne;
    private javax.swing.JMenuBar clientMnuBar;
    private javax.swing.JMenuItem closeMnuItm;
    static javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deleteMovieNameTxtFld;
    private javax.swing.JPanel deleteRecordPnl;
    private javax.swing.JTextField genreidFld;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JMenu helpMnu;
    private javax.swing.JLabel infoLbl;
    javax.swing.JButton loginBtn;
    javax.swing.JPanel loginPnl;
    public static javax.swing.JButton logoutBtn;
    private javax.swing.JMenu mainMnuItm;
    private javax.swing.JScrollPane movieDescripScrlPne;
    private javax.swing.JTextArea moviedescripTxtArea;
    private javax.swing.JTextField movieidFld;
    private javax.swing.JTextField movienameFld;
    private javax.swing.JPasswordField passwordFld;
    javax.swing.JButton searchBtn;
    public static javax.swing.JTextField searchFld;
    private javax.swing.JPanel searchPnl;
    public static javax.swing.JTabbedPane tabAdd;
    private javax.swing.JTextField usernameFld;
    // End of variables declaration//GEN-END:variables
}
