/********************************************************************
*       Filename: searchFrame.java                                  *
*       Author: Tejas Dwarkaram                                     *
*       Date: 14 August 2012, 03:30                                 *
*       Operating System: Windows XP Professional                   *
*       Java Version: JDK 1.5 Update 9                              *
*       Description: Class used to create a new JFrame to house the *
*                    table for the search results                   *
********************************************************************/

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * Class used to display the results of a search
 * @author Tejas Dwarkaram
 * @since JDK 1.5
 * @version 0.1 07/08/2012
 */
public class SearchFrame extends javax.swing.JFrame 
{
    static JPanel searchResultsPnl = new JPanel();
    
    /**
     * Creates new form SearchFrame
     */
    public SearchFrame() 
    {
        initComponents();
        setContentPane(searchResultsPnl);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Results Frame");
        setName("searchFrame");
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Main method which runs a new instance of the constructor
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater
        (
            new Runnable() 
            {
                public void run() 
                {
                    new SearchFrame().setVisible(true);
                }
            }
        );
    }
    
    
    /**
     * Method used to retrieve the results and display them on a table
     * @param data Object[][]
     */
    public static void showResults(Object[][] data)
    {
        String columnNames[] = {"Movie ID","Movie Name","Movie Description","Genre ID" };
        JTable table = new JTable(data, columnNames);
        JScrollPane t00 = new JScrollPane();
        t00.getViewport().add(table);
        searchResultsPnl.add(t00);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
